#!/usr/bin/env bash
#
# Uninstaller for thomasmartinoa/Orrery-dotfiles: undoes what install.sh did.
# See usage() below, or run ./uninstall.sh --help
#
# What it never touches: packages (they may be used by other things; the list
# is printed at the end), enabled services, your own files. A file the rice
# generated is only deleted when it still carries its "GENERATED by orrery"
# line; a link only when it points into this repo.

set -uo pipefail   # no -e: one step that can't finish must not stop the others

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACKAGES=(alacritty gtk hyprland kittyterminal nvim quickshell starship theme zsh)
RETIRED_PACKAGES=(waybar rofi swaync wlogout)
MARK='GENERATED by orrery'

if [[ -t 1 ]] && [[ "${TERM:-dumb}" != "dumb" ]] && [[ -z "${NO_COLOR:-}" ]]; then
  C_DIM=$'\033[2;37m'; C_TXT=$'\033[0;37m'; C_HI=$'\033[1;97m'
  C_OK=$'\033[1;32m';  C_WRN=$'\033[1;33m'; C_ERR=$'\033[1;31m'; C_ACC=$'\033[1;36m'; C_RST=$'\033[0m'
else
  C_DIM=''; C_TXT=''; C_HI=''; C_OK=''; C_WRN=''; C_ERR=''; C_ACC=''; C_RST=''
fi
STEP_N=0; STEP_TOTAL=7
step() { STEP_N=$((STEP_N+1)); printf '\n%s\n' "${C_ACC}[${STEP_N}/${STEP_TOTAL}]${C_RST} ${C_HI}$*${C_RST}"; }
skip() { STEP_N=$((STEP_N+1)); printf '\n%s\n' "${C_DIM}[${STEP_N}/${STEP_TOTAL}] $* (skipped)${C_RST}"; }
info() { printf '  %s %s\n' "${C_ACC}·${C_RST}" "$*"; }
ok()   { printf '  %s %s\n' "${C_OK}✓${C_RST}" "$*"; }
warn() { printf '  %s %s\n' "${C_WRN}!${C_RST}" "$*" >&2; }
die()  { printf '\n  %s %s\n\n' "${C_ERR}✗${C_RST}" "$*" >&2; exit 1; }
tilde() { printf '%s' "${1/#$HOME/\~}"; }
did()  { [[ $DRY_RUN -eq 1 ]] || ok "$@"; }   # report a change only when it was made

usage() {
  cat <<'EOF'
Uninstaller for thomasmartinoa/Orrery-dotfiles

  ./uninstall.sh              remove the rice (asks before starting)
  ./uninstall.sh --dry-run    show what would be removed, change nothing
  ./uninstall.sh --yes        don't ask before starting
  ./uninstall.sh --skip-root  leave the login screen and other /etc, /usr bits
  ./uninstall.sh --help       this text

It removes the config links, the files the theme engine wrote into your apps
(GTK, Qt, btop, VS Code, Firefox, Spotify), the login-screen theme and the
sudo rule, and puts back the configs install.sh moved aside. Packages,
services and this folder stay: delete the folder yourself afterwards.
EOF
}

DRY_RUN=0; YES=0; SKIP_ROOT=0
for arg in "$@"; do
  case "$arg" in
    --dry-run)   DRY_RUN=1 ;;
    --yes|-y)    YES=1 ;;
    --skip-root) SKIP_ROOT=1 ;;
    -h|--help)   usage; exit 0 ;;
    *) usage; die "Unknown option: $arg" ;;
  esac
done

# run <cmd...>: do it, or only say it in a dry run
run() { if [[ $DRY_RUN -eq 1 ]]; then info "would run: $*"; else "$@"; fi; }
# rm_ours <file> [also]: delete a file the rice generated: it carries MARK
# (or, for a file its app rewrites and strips comments from, the text [also])
rm_ours() {
  [[ -f "$1" && ! -L "$1" ]] || return 0
  if grep -qF "$MARK" "$1" 2>/dev/null || { [[ -n ${2:-} ]] && grep -qF "$2" "$1" 2>/dev/null; }; then
    if [[ $DRY_RUN -eq 1 ]]; then info "would remove $(tilde "$1")"; else rm -f -- "$1" && info "removed $(tilde "$1")"; fi
  else
    info "kept $(tilde "$1") (not generated by the rice)"
  fi
}
# a link that points into the repo, or through ~/.config/orrery (the repo's link)
ours_link() { [[ -L "$1" ]] && [[ "$(readlink -m -- "$1")" == "$DOTFILES_DIR"/* || "$(readlink -- "$1")" == "$HOME/.config/orrery/"* ]]; }

printf '\n  %s\n' "${C_HI}Orrery uninstaller${C_RST}"
printf '  %s\n' "${C_DIM}repo $(tilde "$DOTFILES_DIR") · target $(tilde "$HOME") · $([[ $DRY_RUN -eq 1 ]] && echo 'dry run (nothing will change)' || echo 'uninstall')${C_RST}"
[[ $EUID -ne 0 ]] || die "Run this as your own user, not root (it asks for sudo when it needs it)."
command -v stow >/dev/null 2>&1 || die "GNU Stow is not installed (pacman -S stow): it is what removes the links."

if [[ $DRY_RUN -eq 0 && $YES -eq 0 ]]; then
  printf '\n  %s\n' "This removes Orrery from your account. Your files and the packages stay."
  if [[ -t 0 ]]; then
    read -r -p "  $(printf '%s' "${C_ACC}?${C_RST}") Uninstall Orrery? [y/N] " reply </dev/tty || reply=""
  else
    die "Not a terminal, so not asking: re-run with --yes to uninstall."
  fi
  [[ "${reply,,}" == y || "${reply,,}" == yes ]] || die "Nothing changed."
fi

# The theme name, the agent skill dirs and the web apps are read before the
# links that lead to them are gone.
SKILL_DIRS=("$HOME/.claude/skills" "$HOME/.agents/skills" "$HOME/.codex/skills"
            "$HOME/.config/opencode/skills" "$HOME/.gemini/config/skills" "$HOME/.pi/agent/skills")

# ============================================================================
step "Theme files in your apps"
# ============================================================================
# Everything orrery-theme copied into a fixed path an app reads.
for f in "$HOME/.config/gtk-3.0/settings.ini" "$HOME/.config/gtk-4.0/settings.ini" "$HOME/.gtkrc-2.0" \
         "$HOME/.config/kdeglobals" "$HOME/.local/share/color-schemes/Orrery.colors" \
         "$HOME/.config/qt5ct/colors/orrery-theme.conf" "$HOME/.config/qt6ct/colors/orrery-theme.conf" \
         "$HOME/.config/btop/themes/orrery-theme.theme" "$HOME/.config/btop/themes/orrery-aether.theme" \
         "$HOME/.config/fontconfig/conf.d/99-orrery-font.conf"; do
  rm_ours "$f"
done
# qt5ct/qt6ct rewrite their .conf when their window is used, dropping the marker
rm_ours "$HOME/.config/qt5ct/qt5ct.conf" "colors/orrery-theme.conf"
rm_ours "$HOME/.config/qt6ct/qt6ct.conf" "colors/orrery-theme.conf"
# btop: back to its built-in theme
if [[ -f "$HOME/.config/btop/btop.conf" ]] && grep -q '^color_theme = "orrery-' "$HOME/.config/btop/btop.conf"; then
  run sed -i 's/^color_theme = "orrery-.*"/color_theme = "Default"/' "$HOME/.config/btop/btop.conf"
  did "btop uses its default theme."
fi
# Papirus with coloured folders, built by orrery-theme
for d in "$HOME"/.local/share/icons/Papirus*-*; do
  [[ -f "$d/index.theme" ]] && grep -q '(orrery-theme)' "$d/index.theme" || continue
  if [[ $DRY_RUN -eq 1 ]]; then info "would remove $(tilde "$d")"; else rm -rf -- "${d:?}" && info "removed $(tilde "$d")"; fi
done
# GTK4/libadwaita and the portal read these from gsettings
if command -v gsettings >/dev/null 2>&1; then
  for k in color-scheme gtk-theme icon-theme; do run gsettings reset org.gnome.desktop.interface "$k" 2>/dev/null; done
  did "GTK dark/light, theme and icons back to the defaults."
fi
# VS Code (and Code - OSS / VSCodium): the local theme extension and its selection
for ext in "$HOME/.vscode/extensions" "$HOME/.vscode-oss/extensions"; do
  [[ -d "$ext/orrery-theme" ]] || continue
  run rm -rf -- "${ext:?}/orrery-theme"
  if [[ -f "$ext/extensions.json" ]] && command -v jq >/dev/null 2>&1 && [[ $DRY_RUN -eq 0 ]]; then
    tmp="$(mktemp)"
    jq 'map(select(.identifier.id != "local.orrery-theme"))' "$ext/extensions.json" > "$tmp" && mv "$tmp" "$ext/extensions.json" || rm -f "$tmp"
  fi
  did "VS Code theme extension removed from $(tilde "$ext")."
done
for s in "$HOME/.config/Code/User/settings.json" "$HOME/.config/Code - OSS/User/settings.json" "$HOME/.config/VSCodium/User/settings.json"; do
  [[ -f "$s" ]] && grep -q '"workbench.colorTheme": *"Orrery' "$s" || continue
  run sed -i '/"workbench.colorTheme": *"Orrery[^"]*",\{0,1\}/d' "$s"
  did "VS Code back to its default theme ($(tilde "$s"))."
done
# Firefox: the userChrome/userContent files and the user.js block
for ini in "$HOME/.config/mozilla/firefox/profiles.ini" "$HOME/.mozilla/firefox/profiles.ini"; do
  [[ -f "$ini" ]] || continue
  base="$(dirname "$ini")"
  while IFS= read -r prof; do
    [[ "$prof" == /* ]] && dir="$prof" || dir="$base/$prof"
    [[ -d "$dir" ]] || continue
    rm_ours "$dir/chrome/userChrome.css"
    rm_ours "$dir/chrome/userContent.css"
    if [[ -f "$dir/user.js" ]] && grep -q '^// >>> orrery' "$dir/user.js"; then
      run sed -i '/^\/\/ >>> orrery/,/^\/\/ <<< orrery/d' "$dir/user.js"
      did "Firefox prefs block removed ($(tilde "$dir"))."
    fi
  done < <(sed -n 's/^Path=//p' "$ini")
done
# Spotify: undo the Spicetify patch when it carries the rice's theme
sp="$(command -v spicetify || { [[ -x $HOME/.spicetify/spicetify ]] && echo "$HOME/.spicetify/spicetify"; } || true)"
if [[ -n $sp && "$("$sp" config current_theme 2>/dev/null)" == orrery ]]; then
  run "$sp" restore >/dev/null 2>&1
  run "$sp" config current_theme "" color_scheme "" >/dev/null 2>&1
  did "Spotify restored (Spicetify's patch undone)."
fi
# Thunar's "Open Terminal Here" back to its stock command
uca="$HOME/.config/Thunar/uca.xml"
if [[ -f "$uca" ]] && grep -qF "/.local/bin/orrery-terminal %f" "$uca"; then
  run sed -i "s|[^<>]*/.local/bin/orrery-terminal %f|exo-open --working-directory %f --launch TerminalEmulator|" "$uca"
  did "Thunar's \"Open Terminal Here\" back to the default."
fi

# ============================================================================
step "Shell, agents and web apps"
# ============================================================================
# notification daemons install.sh masked so the shell could own notifications
for svc in /usr/share/dbus-1/services/*.service; do
  grep -qx 'Name=org.freedesktop.Notifications' "$svc" 2>/dev/null || continue
  unit="$(sed -n 's/^SystemdService=//p' "$svc")"
  [[ -n $unit && "$(systemctl --user is-enabled "$unit" 2>/dev/null)" == masked ]] || continue
  run systemctl --user unmask "$unit" >/dev/null 2>&1 && did "${unit%.service} can start again."
done
# the /orrery skill links in the coding agents' skill dirs
for d in "${SKILL_DIRS[@]}"; do
  for l in "$d"/*; do
    ours_link "$l" || continue
    if [[ $DRY_RUN -eq 1 ]]; then info "would remove $(tilde "$l")"; else rm -f -- "$l" && info "removed $(tilde "$l")"; fi
  done
done
# web apps: their launchers need orrery-webapp, which is about to go
apps=()
for f in "$HOME"/.local/share/applications/*.desktop; do
  grep -qx 'X-Orrery-WebApp=true' "$f" 2>/dev/null && apps+=("$f")
done
if [[ ${#apps[@]} -gt 0 ]]; then
  info "${#apps[@]} web app(s): $(for f in "${apps[@]}"; do sed -n 's/^Name=//p' "$f" | head -1; done | paste -sd, -)"
  info "They open through orrery-webapp, which is part of the rice: their launchers stop working."
  reply="n"
  if [[ $DRY_RUN -eq 0 && -t 0 ]]; then
    read -r -p "  $(printf '%s' "${C_ACC}?${C_RST}") Remove them, with their saved logins? [y/N] " reply </dev/tty || reply="n"
  fi
  if [[ "${reply,,}" == y || "${reply,,}" == yes ]]; then
    for f in "${apps[@]}"; do
      id="$(basename "$f" .desktop)"
      rm -f -- "$f" "$HOME/.local/share/icons/hicolor/256x256/apps/$id.png"
      rm -rf -- "${HOME:?}/.local/share/orrery/webapps/${id:?}"
    done
    ok "Web apps removed."
  else
    info "Kept (launchers in ~/.local/share/applications, logins in ~/.local/share/orrery/webapps)."
  fi
fi
# the shell's own state: launcher history, last wallpapers, the diagnostics report
if [[ -d "$HOME/.local/state/orrery" ]]; then
  run rm -rf -- "${HOME:?}/.local/state/orrery" && did "Removed ~/.local/state/orrery."
fi

# ============================================================================
step "Config links"
# ============================================================================
pkgs=()
for p in "${PACKAGES[@]}"; do [[ -d "$DOTFILES_DIR/$p" ]] && pkgs+=("$p"); done
if [[ $DRY_RUN -eq 1 ]]; then
  n="$(stow --no --verbose=2 -D --target="$HOME" --dir="$DOTFILES_DIR" "${pkgs[@]}" 2>&1 | grep -c '^UNLINK' || true)"
  info "would remove $n link(s) from: ${pkgs[*]}"
else
  stow -D --target="$HOME" --dir="$DOTFILES_DIR" "${pkgs[@]}" && ok "Links removed: ${pkgs[*]}." \
    || warn "stow could not remove every link (see above)."
fi
# links of packages from earlier versions, and any other link into the repo
# stow didn't know about (it only removes what the current packages contain)
for old in "${RETIRED_PACKAGES[@]}"; do
  ours_link "$HOME/.config/$old" && run rm -f -- "$HOME/.config/$old"
done
[[ $DRY_RUN -eq 1 ]] || while IFS= read -r l; do
  [[ -n $l ]] || continue
  if [[ $DRY_RUN -eq 1 ]]; then info "would remove $(tilde "$l")"; else rm -f -- "$l" && info "removed $(tilde "$l")"; fi
done < <(find "$HOME/.config" "$HOME/.local/bin" "$HOME/.local/share" -maxdepth 3 -type l 2>/dev/null \
          | while IFS= read -r l; do [[ "$(readlink -m -- "$l")" == "$DOTFILES_DIR"/* ]] && printf '%s\n' "$l"; done)

# ============================================================================
step "Your configs from before"
# ============================================================================
# install.sh moved what was in its way to ~/.config/orrery-backup-<date> (the
# rice's old name used hypr-dotfiles-backup-<date>). The OLDEST one holds the
# configs from before the first install; put back whatever now has no file.
backup="$(ls -d "$HOME"/.config/orrery-backup-* "$HOME"/.config/hypr-dotfiles-backup-* 2>/dev/null \
          | sed 's/.*-\([0-9]\{8\}-[0-9]\{6\}\)$/\1 &/' | sort | head -1 | cut -d' ' -f2-)"
if [[ -z $backup ]]; then
  ok "No backup from install.sh: nothing to put back."
else
  restored=0
  while IFS= read -r f; do
    rel="${f#"$backup"/}"
    # (a dry run removed nothing yet: what steps 1 and 3 would remove counts as free)
    if [[ -e "$HOME/$rel" || -L "$HOME/$rel" ]] && \
       ! { [[ $DRY_RUN -eq 1 ]] && { [[ "$(readlink -m -- "$HOME/$rel")" == "$DOTFILES_DIR"/* ]] || grep -qsF "$MARK" "$HOME/$rel"; }; }; then
      info "kept ~/$rel (something is there now)"; continue
    fi
    if [[ $DRY_RUN -eq 1 ]]; then info "would restore ~/$rel"
    else mkdir -p "$(dirname "$HOME/$rel")" && cp -a -- "$f" "$HOME/$rel" && info "restored ~/$rel"; fi
    restored=$((restored+1))
  done < <(find "$backup" -mindepth 1 \( -type f -o -type l \) 2>/dev/null)
  ok "Put back $restored file(s) from $(tilde "$backup") (the backup itself stays)."
fi

# ============================================================================
# Root: the login screen, the sudo rule and its helper, root's GTK theme, the
# Chromium colour policy, the headset-mic sleep hook. Each only when it is the
# rice's (SDDM drop-ins compared byte for byte with the repo's).
# ============================================================================
root_files=()
[[ -d /usr/share/sddm/themes/orrery ]] && root_files+=(/usr/share/sddm/themes/orrery)
[[ -f /usr/share/sddm/hyprland.lua ]] && cmp -s /usr/share/sddm/hyprland.lua "$DOTFILES_DIR/sddm/hyprland.lua" && root_files+=(/usr/share/sddm/hyprland.lua)
for c in "$DOTFILES_DIR"/sddm/sddm.conf.d/*.conf; do
  t="/etc/sddm.conf.d/$(basename "$c")"
  [[ -f $t ]] && cmp -s "$t" "$c" && root_files+=("$t")
done
# names only the rice uses; some (the sudo rule, /root) can't be seen without
# sudo, so they're removed whenever the rice's helper or theme is installed
[[ -e /usr/local/bin/orrery-root-sync || -e /usr/lib/systemd/system-sleep/orrery-headset-mic || ${#root_files[@]} -gt 0 ]] && \
  root_files+=(/usr/local/bin/orrery-root-sync /etc/sudoers.d/orrery-theme /usr/lib/systemd/system-sleep/orrery-headset-mic
               /etc/chromium/policies/managed/orrery-color.json /etc/opt/chrome/policies/managed/orrery-color.json
               /etc/brave/policies/managed/orrery-color.json /root/.config/orrery
               /etc/chromium/policies/managed/hypr-theme-color.json)   # the rice's old name
if [[ $SKIP_ROOT -eq 1 ]]; then
  skip "Login screen and system files"
elif [[ ${#root_files[@]} -eq 0 ]]; then
  step "Login screen and system files"; ok "Nothing of the rice's outside your home."
else
  step "Login screen and system files"
  for f in "${root_files[@]}"; do info "$f"; done
  if [[ $DRY_RUN -eq 1 ]]; then
    info "would remove these with sudo"
  elif sudo -v; then
    sudo rm -rf -- "${root_files[@]}"
    # root's GTK config written by orrery-root-sync, only where it still imports the rice's palette
    for f in /root/.config/gtk-3.0/gtk.css /root/.config/gtk-4.0/gtk.css; do
      sudo grep -qs 'orrery/current/palette.css' "$f" && sudo rm -f -- "$f"
    done
    for f in /root/.config/gtk-3.0/settings.ini /root/.config/gtk-4.0/settings.ini /root/.gtkrc-2.0 /root/.config/kdeglobals; do
      sudo grep -qsF "$MARK" "$f" && sudo rm -f -- "$f"
    done
    ok "Removed. The login screen falls back to SDDM's default theme."
  else
    warn "Skipped: no sudo. Run ./uninstall.sh again when you can, or --skip-root to leave these."
  fi
fi

# ============================================================================
step "Packages and services"
# ============================================================================
info "Left installed, as other things may use them. Remove any you don't want:"
info "  sudo pacman -Rns <package>"
info "The rice's own: quickshell hyprsunset batsignal cliphist qt5ct qt6ct adw-gtk-theme papirus-icon-theme"
info "NetworkManager, Bluetooth, power profiles and SDDM stay enabled."

# ============================================================================
step "Done"
# ============================================================================
if [[ $DRY_RUN -eq 1 ]]; then
  ok "Dry run complete: nothing was changed."
  exit 0
fi
# the running session: stop the shell (it would keep drawing from memory) and
# reload Hyprland onto the config it has now (yours, or its own default)
pkill -x qs 2>/dev/null; pkill -x quickshell 2>/dev/null; pkill -x hypridle 2>/dev/null
if [[ -n ${HYPRLAND_INSTANCE_SIGNATURE:-} ]] && command -v hyprctl >/dev/null 2>&1; then
  hyprctl reload >/dev/null 2>&1 && info "Hyprland reloaded with $( [[ -e $HOME/.config/hypr/hyprland.lua || -e $HOME/.config/hypr/hyprland.conf ]] && echo 'your previous config' || echo 'no config: it makes a default one')."
fi
ok "Orrery is uninstalled."
info "This folder is still here, with any themes you made in theme/.config/orrery/themes/."
info "Delete it when you don't need it:  rm -rf $(tilde "$DOTFILES_DIR")"
info "Reboot (or log out) so Hyprland and your apps start without the rice."
info "Hyprland writes a fresh default config the next time it starts if you had none before."
