#!/usr/bin/env bash
#
# A real install, uninstall and reinstall, as a new user would do it, checked
# step by step. GitHub runs it in a fresh Arch Linux container
# (.github/workflows/ci.yml): run it as an ordinary user with passwordless
# sudo, from a clone in that user's home. It answers yes to backing up what
# is in the way (--migrate), as you would. Not for your own machine: it
# uninstalls the rice from the account it runs in.
#
#   tests/install-test.sh [--stow-only]   (--stow-only: packages already
#                                         installed, no sudo needed; any
#                                         install.sh flag is passed on)

set -uo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOG="$(mktemp)"
fails=0
pass() { printf '  ok    %s\n' "$*"; }
bad()  { printf '  FAIL  %s\n' "$*"; fails=$((fails+1)); }
check() { local what="$1"; shift; if "$@" >/dev/null 2>&1; then pass "$what"; else bad "$what"; fi; }
section() { printf '\n== %s\n' "$*"; }
# run <label> <cmd…>: run, keep the output, show it only when it fails
run() {
  local label="$1"; shift
  if "$@" </dev/null >"$LOG" 2>&1; then pass "$label"
  else bad "$label (exit $?)"; sed 's/^/      /' "$LOG" | tail -40; fi
}

[[ $EUID -ne 0 ]] || { echo "run as an ordinary user"; exit 2; }
EXTRA=("$@")
cd "$REPO"

# links anywhere under ~ that resolve into the repo (the installer's work)
links_into_repo() {
  find "$HOME" -maxdepth 5 -type l -not -path "$REPO/*" 2>/dev/null \
    | while IFS= read -r l; do [[ "$(readlink -m -- "$l")" == "$REPO"/* ]] && printf '%s\n' "$l"; done
}
generated_left() { grep -rlsF 'GENERATED by orrery' "$HOME/.config" "$HOME/.gtkrc-2.0" "$HOME/.local/share" 2>/dev/null | grep -v "^$REPO/"; }

section "Packages"
mapfile -t pkgs < <(sed -n '/^PKGS_REPO=(/,/^)/p' install.sh | sed -e 's/#.*//' -e 's/PKGS_REPO=(//' -e 's/)//' | tr ' ' '\n' | sed '/^$/d')
missing=()
for p in "${pkgs[@]}"; do pacman -Si "$p" >/dev/null 2>&1 || missing+=("$p"); done
if [[ ${#missing[@]} -eq 0 ]]; then pass "all ${#pkgs[@]} packages are in the official repos"
else bad "not in the repos: ${missing[*]}"; fi

section "Install"
run "install.sh --dry-run" ./install.sh --dry-run
run "install.sh" ./install.sh --skip-root --no-reboot --migrate "${EXTRA[@]}"
grep -q 'Installed\.' "$LOG" && pass "it reports Installed." || bad "no 'Installed.' at the end"
check "Hyprland's config links into the repo"   test "$(readlink -f ~/.config/hypr/hyprland.lua)" = "$REPO/hyprland/.config/hypr/hyprland.lua"
check "~/.config/quickshell links into the repo"  test "$(readlink -f ~/.config/quickshell)" = "$REPO/quickshell/.config/quickshell"
check "orrery-theme is on ~/.local/bin"           test -x ~/.local/bin/orrery-theme
check "~/.local is a real directory (not folded)" test ! -L ~/.local
check "a theme is rendered"                       test -s ~/.config/orrery/current/colors.json
check "the theme is Eclipse"                      grep -qx eclipse ~/.config/orrery/current/theme.name
check "the wallpaper link points at an image"     test -s "$(readlink -f ~/.config/orrery/current/background)"
check "GTK settings are written"                  grep -q 'GENERATED by orrery' ~/.config/gtk-3.0/settings.ini
check "Qt uses Fusion"                            grep -qx 'style=Fusion' ~/.config/qt6ct/qt6ct.conf
check "the /orrery skill is linked"               test -e ~/.claude/skills/orrery/SKILL.md
check "Hyprland's config has no Lua syntax error" luac -p ~/.config/hypr/hyprland.lua
for t in eclipse zenith catppuccin-mocha cassini; do
  run "orrery-theme set $t" ~/.local/bin/orrery-theme set "$t"
  check "  $t: wallpaper is one of its own" bash -c "[[ \$(readlink -f ~/.config/orrery/current/background) == */themes/$t/backgrounds/* ]]"
done
run "orrery-theme set eclipse (back)" ~/.local/bin/orrery-theme set eclipse

section "Colours from wallpaper"
WT=~/.local/bin/orrery-wall-theme
THEMES=~/.config/orrery/themes
gen_ok() {   # gen_ok <label>: the generated theme is on, valid and readable
  check "  $1: the Wallpaper theme is on" grep -qx wallpaper ~/.config/orrery/current/theme.name
  run "  $1: it passes the theme checks" python3 "$REPO/tests/check.py" --theme "$THEMES/wallpaper"
}
for t in eclipse zenith catppuccin-mocha cassini; do
  img="$(find "$THEMES/$t/backgrounds/" -maxdepth 1 -type f \( -name '*.jpg' -o -name '*.png' \) | head -1)"
  run "apply $t's wallpaper (auto)" "$WT" apply "$img" --mode auto --style soft
  gen_ok "$t"
  check "  $t: its wallpaper is on screen" test "$(readlink -f ~/.config/orrery/current/background)" = "$(readlink -f "$img")"
done
check "the fog (white) makes a light theme"       bash -c "$WT apply $THEMES/zenith/backgrounds/*.jpg >/dev/null && grep -q 'mode = \"light\"' $THEMES/wallpaper/colors.toml"
check "the mountain (grey) makes a grey theme"    bash -c "$WT apply $THEMES/eclipse/backgrounds/*.png >/dev/null && grep -q 'hued = false' $THEMES/wallpaper/colors.toml"
cas="$(ls "$THEMES"/cassini/backgrounds/*.jpg | head -1)"
for o in "--style faithful" "--style vivid" "--mode dark" "--mode light" "--accent 2"; do
  # shellcheck disable=SC2086
  run "cassini $o" "$WT" apply "$cas" $o
  gen_ok "cassini $o"
done
for a in 0 1 2 3; do
  check "preview, main colour $a" bash -c "$WT preview '$cas' --accent $a | python3 -c 'import json,sys; d=json.load(sys.stdin); assert d[\"colors\"][\"accent_bright\"] == d[\"candidates\"][d[\"accent\"]]'"
done
tmpimg="$(mktemp -d)/outside.jpg"; cp "$cas" "$tmpimg"
run "use a picture from elsewhere" "$WT" use "$tmpimg"
check "  it was copied into ~/Pictures/Wallpapers"   test -f ~/Pictures/Wallpapers/outside.jpg
check "  the original is still there"               test -f "$tmpimg"
check "  the copy is on screen"                     test "$(readlink -f ~/.config/orrery/current/background)" = "$(readlink -f ~/Pictures/Wallpapers/outside.jpg)"
run "turn it off" "$WT" off
check "  back to the theme from before"            grep -qx eclipse ~/.config/orrery/current/theme.name
run "settings are remembered while off" "$WT" config --mode light
run "turn it on again" "$WT" on
check "  it uses your last picture, not the theme's"  test "$(readlink -f ~/.config/orrery/current/background)" = "$(readlink -f ~/Pictures/Wallpapers/outside.jpg)"
check "  and the mode you chose"                      grep -q 'mode = "light"' "$THEMES/wallpaper/colors.toml"
run "accent 2 for one picture" "$WT" apply "$cas" --accent 2
run "another picture" "$WT" apply ~/Pictures/Wallpapers/outside.jpg
check "  the first keeps its accent"                  bash -c "$WT apply '$cas' | python3 -c 'import json,sys; assert json.load(sys.stdin)[\"accent\"] == 2'"
run "off again" "$WT" off
section "Blur and transparency"
LL=~/.config/hypr/modules/look.local.lua
run "orrery-look blur off" ~/.local/bin/orrery-look blur off
check "  it's in Hyprland's override file"        grep -q 'enabled = false' "$LL"
run "orrery-look blur strong" ~/.local/bin/orrery-look blur strong
check "  blur is on again, size 14"                grep -q 'enabled = true, size = 14' "$LL"
run "orrery-look opacity 80" ~/.local/bin/orrery-look opacity 80
check "  80 % focused, 60 % the rest"              grep -q 'active_opacity = 0.8, inactive_opacity = 0.6' "$LL"
run "orrery-border radius 8 (same file)" ~/.local/bin/orrery-border radius 8
check "  corners and blur both kept"               grep -q 'rounding = 8, blur = { enabled = true, size = 14' "$LL"
run "orrery-look reset" ~/.local/bin/orrery-look reset
run "orrery-border reset" ~/.local/bin/orrery-border reset
check "  the override file is gone"                test ! -e "$LL"

run "install.sh again (safe to re-run)" ./install.sh --skip-root --no-reboot --migrate "${EXTRA[@]}"

section "Uninstall"
run "uninstall.sh --dry-run" ./uninstall.sh --dry-run
run "uninstall.sh" ./uninstall.sh --yes --skip-root
left="$(links_into_repo)"
[[ -z $left ]] && pass "no links into the repo are left" || bad "links left: $(tr '\n' ' ' <<<"$left")"
left="$(generated_left)"
[[ -z $left ]] && pass "no generated files are left" || bad "generated files left: $(tr '\n' ' ' <<<"$left")"
check "orrery-theme is gone from ~/.local/bin" test ! -e ~/.local/bin/orrery-theme
run "uninstall.sh again (nothing to do)" ./uninstall.sh --yes --skip-root

section "Reinstall"
run "install.sh after uninstall" ./install.sh --stow-only --skip-root --no-reboot --migrate
check "Hyprland's config links into the repo again" test "$(readlink -f ~/.config/hypr/hyprland.lua)" = "$REPO/hyprland/.config/hypr/hyprland.lua"
check "a theme is rendered again"                 test -s ~/.config/orrery/current/colors.json

rm -f "$LOG"
printf '\n%s\n' "$([[ $fails -eq 0 ]] && echo 'All install tests passed.' || echo "$fails install test(s) failed.")"
exit $(( fails > 0 ))
