-- GENERATED by orrery-theme — theme: {{ name }} ({{ mode }}). Do not edit.
-- Loaded from ~/.config/hypr/modules/decorations.lua via dofile().
hl.config({
	general = {
		col = {
			active_border   = "{{ accent_bright | hypr 0.67 }}",
			inactive_border = "{{ mix bg4 accent_dim 60% | hypr 0.67 }}",
		},
	},
	decoration = {
		rounding = {{ radius }},   -- the theme's corners; orrery-border's choice (look.local.lua) loads after
		shadow = {
			color = "{{ mix bg0 bg1 60% | hypr 0.93 }}",
		},
	},
	-- what shows behind everything until the shell's wallpaper is up (login)
	misc = {
		background_color = "{{ bg0 | hypr 1 }}",
	},
})
